// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Fela = require("fela");
var Curry = require("bs-platform/lib/js/curry.js");
var ReactFela = require("react-fela");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function createComponent(rule, baseElement, passThrough, extend, props, children) {
  var reactClass;
  if (passThrough !== undefined) {
    var be = baseElement !== undefined ? baseElement : /* `String */[
        -976970511,
        "div"
      ];
    reactClass = ReactFela.createComponent(rule, be[1], passThrough);
  } else {
    reactClass = baseElement !== undefined ? ReactFela.createComponent(rule, baseElement[1]) : ReactFela.createComponent(rule);
  }
  if (extend !== undefined) {
    return ReasonReact.wrapJsForReason(reactClass, Curry._1(extend, props), children);
  } else {
    return ReasonReact.wrapJsForReason(reactClass, props, children);
  }
}

function createComponentWithProxy(rule, baseElement, passThrough, extend, props, children) {
  var reactClass;
  if (passThrough !== undefined) {
    var be = baseElement !== undefined ? baseElement : /* `String */[
        -976970511,
        "div"
      ];
    reactClass = ReactFela.createComponentWithProxy(rule, be[1], passThrough);
  } else {
    reactClass = baseElement !== undefined ? ReactFela.createComponentWithProxy(rule, baseElement[1]) : ReactFela.createComponentWithProxy(rule);
  }
  if (extend !== undefined) {
    return ReasonReact.wrapJsForReason(reactClass, Curry._1(extend, props), children);
  } else {
    return ReasonReact.wrapJsForReason(reactClass, props, children);
  }
}

function withTheme(component, make, children) {
  var reactClass = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
          return Curry._2(make, jsProps.theme, children);
        }));
  var reactClass$1 = ReactFela.withTheme(reactClass, undefined);
  return ReasonReact.wrapJsForReason(reactClass$1, { }, children);
}

function connect(rules, component, make, props, children) {
  var reactClass = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
          return Curry._2(make, jsProps.styles, children);
        }));
  var makeReactClass = ReactFela.connect(rules[1]);
  var reactClass$1 = Curry._1(makeReactClass, reactClass);
  return ReasonReact.wrapJsForReason(reactClass$1, props, children);
}

var defaultRenderer = Fela.createRenderer();

function make($staropt$star, children) {
  var renderer = $staropt$star !== undefined ? Js_primitive.valFromOption($staropt$star) : defaultRenderer;
  return ReasonReact.wrapJsForReason(ReactFela.Provider, {
              renderer: renderer
            }, children);
}

var Provider = /* module */[
  /* defaultRenderer */defaultRenderer,
  /* make */make
];

function make$1(theme, $staropt$star, children) {
  var overwrite = $staropt$star !== undefined ? $staropt$star : false;
  return ReasonReact.wrapJsForReason(ReactFela.ThemeProvider, {
              theme: theme,
              overwrite: overwrite
            }, children);
}

var ThemeProvider = /* module */[/* make */make$1];

exports.createComponent = createComponent;
exports.createComponentWithProxy = createComponentWithProxy;
exports.withTheme = withTheme;
exports.connect = connect;
exports.Provider = Provider;
exports.ThemeProvider = ThemeProvider;
/* defaultRenderer Not a pure module */
