// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fela        = require("fela");
var Curry       = require("bs-platform/lib/js/curry.js");
var Js_boolean  = require("bs-platform/lib/js/js_boolean.js");
var ReactFela   = require("react-fela");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function createComponent(rule, baseElement, passThrough, extend, props, children) {
  var reactClass;
  if (passThrough) {
    var be = baseElement ? baseElement[0] : /* `String */[
        -976970511,
        "div"
      ];
    reactClass = ReactFela.createComponent(rule, be[1], passThrough[0]);
  } else {
    reactClass = baseElement ? ReactFela.createComponent(rule, baseElement[0][1]) : ReactFela.createComponent(rule);
  }
  var props$1 = extend ? Object.assign(props, Curry._1(extend[0], props)) : props;
  return ReasonReact.wrapJsForReason(reactClass, props$1, children);
}

function createComponentWithProxy(rule, baseElement, passThrough, extend, props, children) {
  var reactClass;
  if (passThrough) {
    var be = baseElement ? baseElement[0] : /* `String */[
        -976970511,
        "div"
      ];
    reactClass = ReactFela.createComponentWithProxy(rule, be[1], passThrough[0]);
  } else {
    reactClass = baseElement ? ReactFela.createComponentWithProxy(rule, baseElement[0][1]) : ReactFela.createComponentWithProxy(rule);
  }
  var props$1 = extend ? Object.assign(props, Curry._1(extend[0], props)) : props;
  return ReasonReact.wrapJsForReason(reactClass, props$1, children);
}

function withTheme(component, make, children) {
  var reactClass = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
          return Curry._2(make, jsProps.theme, children);
        }));
  var reactClass$1 = ReactFela.withTheme(reactClass, undefined);
  return ReasonReact.wrapJsForReason(reactClass$1, { }, children);
}

function connect(rules, component, make, props, children) {
  var reactClass = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
          return Curry._2(make, jsProps.styles, children);
        }));
  var makeReactClass = ReactFela.connect(rules[1]);
  var reactClass$1 = Curry._1(makeReactClass, reactClass);
  return ReasonReact.wrapJsForReason(reactClass$1, props, children);
}

var defaultRenderer = Fela.createRenderer();

function make($staropt$star, children) {
  var renderer = $staropt$star ? $staropt$star[0] : defaultRenderer;
  return ReasonReact.wrapJsForReason(ReactFela.Provider, {
              renderer: renderer
            }, children);
}

var Provider = /* module */[
  /* defaultRenderer */defaultRenderer,
  /* make */make
];

function make$1(theme, $staropt$star, children) {
  var overwrite = $staropt$star ? $staropt$star[0] : /* false */0;
  return ReasonReact.wrapJsForReason(ReactFela.ThemeProvider, {
              theme: theme,
              overwrite: Js_boolean.to_js_boolean(overwrite)
            }, children);
}

var ThemeProvider = /* module */[/* make */make$1];

exports.createComponent          = createComponent;
exports.createComponentWithProxy = createComponentWithProxy;
exports.withTheme                = withTheme;
exports.connect                  = connect;
exports.Provider                 = Provider;
exports.ThemeProvider            = ThemeProvider;
/* defaultRenderer Not a pure module */
